### ISSUE TITLE
Finally, a real gliz!

### ISSUE THREAD

**Issue by VillainsRule4000** [therealgliz/blooket-hacks#371]
THANK YOU, and unobfuscated stuff as well!
This will change Blooket forever.

(the skids are gonna go crazy)

If you would like, I could import this to a Glitch or Repl site to help people with blocked access to Github!

**Comment by rxzyx** [comment]
See, I was right.

**Comment by VillainsRule4000** [comment]
@rxzyx I knew, I was debating...you had essentially change my mind

**Comment by l2vy7** [comment]
This is NOT a real account.

Glizzy has actually deleted his Twitter account, and "therealgliz" actually @kixxzy :joy: is now using a new Twitter account under his name for proof.

This is the last available snapshot of his ACTUAL account.

https://web.archive.org/web/20210604202113/https://twitter.com/glizuwu

**Comment by therealgliz** [comment]
> See, I was right.

Join my discord needa talk to you about your hacks

**Comment by rxzyx** [comment]
I joined

**Comment by VillainsRule4000** [comment]
@l2vy7 I trust you, and if l2vy7 has a deleted comment, it means he said you were fake. @therealgliz faker

**Comment by therealgliz** [comment]
> @l2vy7 I trust you, and if l2vy7 has a deleted comment, it means he said you were fake. @therealgliz faker

I'm the real one, join the discord server and find out? I deleted the comment from I2vy7 cause he made a false assumption and we cleared out in the discord server.

**Comment by VillainsRule4000** [comment]
@therealgliz Then I can ask him personally!

**Comment by KokoLuvsCats** [comment]
gliz got banned or smth so made a new acc. this ain't fake
