### ISSUE TITLE
Are you lol-jude?

### ISSUE THREAD

**Issue by Beep404-Boop404** [therealgliz/blooket-hacks#384]

**Comment by Glixxzzy** [comment]
no lol-jude gave the repo to the original gliz

**Comment by lmfao-jude** [comment]
no i am

**Comment by Glixxzzy** [comment]
not that jude

**Comment by lmfao-jude** [comment]
no im lol jude

**Comment by Beep404-Boop404** [comment]
wait what- 
Is lmfao-jude lol-jude?

**Comment by Glixxzzy** [comment]
no
lol-jude the person pretending to be gliz
not lmfao-jude the coder
