### ISSUE TITLE
Add tokens doesn't work

### ISSUE THREAD

**Issue by Apersonvr** [therealgliz/blooket-hacks#413]
Please fix "Add tokens" as it doesn't work right now

**Comment by sdkhfgvwierg** [comment]
The script byitself or the bookmarklet version.

**Comment by sdkhfgvwierg** [comment]
@VillainsRule4000 should help you soon hes a really cool guy who helps people fix their issues with the scripts.

**Comment by Apersonvr** [comment]
> The script byitself or the bookmarklet version.

The bookmarklet version.

**Comment by VillainsRule4000** [comment]
@Apersonvr This works fine as a bookmarklet for me. Are you sure this is an error with the hack itself? I just used it on a test alt two minutes ago with no issue.

**Comment by VillainsRule4000** [comment]
> @VillainsRule4000 should help you soon hes a really cool guy who helps people fix their issues with the scripts.

🤣

**Comment by sdkhfgvwierg** [comment]
Sorry I should have let you do that😔

**Comment by Apersonvr** [comment]
It works now i guess I wasn't using it right the first time
