### ISSUE TITLE
Encoder

### ISSUE THREAD

**Issue by DummyPotato** [therealgliz/blooket-hacks#420]
What encoder did you guys use before? The current scripts aren't encoded but the previous ones were

**Comment by VillainsRule4000** [comment]
One on the webs :)

**Comment by DummyPotato** [comment]
Which one tho lol

**Comment by VillainsRule4000** [comment]
Idk, obfuscator.io maybe?

**Comment by DummyPotato** [comment]
Good enough for me :)
