### ISSUE TITLE
Yo @VilliansRule4000 you good bro?

### ISSUE THREAD

**Issue by YaBoyMH** [therealgliz/blooket-hacks#446]
Every day I see more and more useless issues, and everything seems like it is falling apart?

**Comment by sdkhfgvwierg** [comment]
Also is he the real gliz who coded all of this or are these people lying?

**Comment by VillainsRule4000** [comment]
1. I don't run this. Answering issues is a hobby. I cannot close issues, only answer them.
2. I am unsure if this is the real gliz.

**Comment by YaBoyMH** [comment]
Hey btw my old name was sdkhfgvwierg you might remember me I try to help people find blooket hacks now but no one looks at my repository you should check it out!
