### ISSUE TITLE
[README] repository archived

### ISSUE THREAD

**Issue by VillainsRule4000** [therealgliz/blooket-hacks#463]
## Guys, the repository isn't gonna be updated.
If this is the real gliz, then they're done with Blooket. Nothing will be updated.
If they're a random skid, they can't code, what do you expect lol

## Working Scripts
You're gonna ask, check these repos: 
[Jod](https://github.com/Minesraft2/Blooket-Cheats)
[Goose](https://github.com/GooseterV/Blooket)
[also, here's some Blooket SRC from Greenlio](https://github.com/Greenlio/blooket-src)

All of these are made by scripters who made each script themselves.

## Basic Script Fix
Replace the following lines:
```js
            function reactHandler() {
                return Object.values(document.querySelector('#app > div > div'))[1].children[1]._owner;
            };
```
with the following lines:
```js
            function reactHandler() {
                return Object.values(document.querySelector('#app > div > div'))[1].children[0]._owner;
            };
```
If you don't see these lines, don't bother.

**Comment by Greenlio** [comment]
👍

**Comment by MrNoobb** [comment]
👍
Thank You!

**Comment by NotDarkn** [comment]
yup. 👍

**Comment by Sanity-Z** [comment]
👍

**Comment by Greenlio** [comment]
> I just looked into the issue with gamemode scripts. The function `reactHandler()` changed, it now should be `children[0]` instead of `children[1]`. Replacing this before you run the script should fix all gamemode hacks.

(everyone of special relevance already knew this)

**Comment by VillainsRule4000** [comment]
> > I just looked into the issue with gamemode scripts. The function `reactHandler()` changed, it now should be `children[0]` instead of `children[1]`. Replacing this before you run the script should fix all gamemode hacks.
> 
> (everyone of special relevance already knew this)

lol

**Comment by Greenlio** [comment]
> > > I just looked into the issue with gamemode scripts. The function `reactHandler()` changed, it now should be `children[0]` instead of `children[1]`. Replacing this before you run the script should fix all gamemode hacks.
> > 
> > 
> > (everyone of special relevance already knew this)
> 
> lol

You had and have no reason to use reactHandler(), the function was only ever made for use in a GUI as consistently calling the variable would simply not look good. It's just a function returning something. You can set it to a variable and make your code look much better.

**Comment by VillainsRule4000** [comment]
> > > > I just looked into the issue with gamemode scripts. The function `reactHandler()` changed, it now should be `children[0]` instead of `children[1]`. Replacing this before you run the script should fix all gamemode hacks.
> > > 
> > > 
> > > (everyone of special relevance already knew this)
> > 
> > 
> > lol
> 
> You had and have no reason to use reactHandler(), the function was only ever made for use in a GUI as consistently calling the variable would simply not look good. It's just a function returning something. You can set it to a variable and make your code look much better.

Fair point, I used the format in each script. Since replacing 3 lines is much easier then removing parenthesis (if you find this silly, what is this PR lol https://github.com/rxzyx/prodigy-hack/pull/27). This ignorance just proves further that gliz has no coding talent whatsoever.

**Comment by fowntain** [comment]
bump

**Comment by VillainsRule4000** [comment]
too far down in issues list to be useful
