### ISSUE TITLE
SINCE THIS GUY ISNT DOIN HACKS ANYMORE USE THIS GITHUB REPO IT HAS ALL THE HACKS AND I WILL BE ADDING CONTRIBUTERS SO COMMENT YOUR NAME BELOW HERE IS THE LINK: https://github.com/THEBEAST112209/New-Blooket-Hacks

### ISSUE THREAD

**Issue by THEBEAST112209** [therealgliz/blooket-hacks#481]

**Comment by VillainsRule4000** [comment]
:skull:
Maybe at least give credit to the original hack maker, dummy?
https://github.com/Minesraft2/Blooket-Cheats

**Comment by Sanity-Z** [comment]
> 💀 Maybe at least give credit to the original hack maker, dummy? https://github.com/Minesraft2/Blooket-Cheats

Frfr

**Comment by THEBEAST112209** [comment]
nah he copied my code not the other way around

**Comment by VillainsRule4000** [comment]
Yours was made 5 days ago, his 9. I can read.

**Comment by VillainsRule4000** [comment]
If you are a real Blooket coder, tell me the API base URL.
Don't try googling it, it's not there.

**Comment by VillainsRule4000** [comment]
Actually, you need the React Dev Tools extension to hack Blooket properly.
You're not a dev, Java is not Javascript and it is spelled HTML rather than HML.
Delete the repo before someone files a DCMA takedown for skidding.

You have one last chance: what is the Blooket API base URL.

**Comment by Minesraft2** [comment]
> nah he copied my code not the other way around

💀 💀 💀 you can't be older than 9

**Comment by arabbbbb** [comment]
FR BRUH 😭

**Comment by Youpromisemysonfreebobux** [comment]
lmfaoooo
brroooo
