### ISSUE TITLE
READ BEFORE ISSUE

### ISSUE THREAD

**Issue by monkxy** [therealgliz/blooket-hacks#492]
At this point it's clear this person is fake, regardless it won't be maintained look for other hacks rather than making issues, I make some working ones if you want to check those out [here](https://github.com/Jude-Gideon/Blooket)

**Comment by godlygamer123** [comment]
i like yours

**Comment by Minesraft2** [comment]
> i like yours

His were stolen from rzx and me, if you want some actually maintained and original cheats go here
https://github.com/Minesraft2/Blooket-Cheats

**Comment by Jude-Gideon** [comment]
they were not

**Comment by fowntain** [comment]
> they were not

Nice try kiddo, no one believes you. Hate skids like this

**Comment by Jude-Gideon** [comment]
> > they were not
> 
> Nice try kiddo, no one believes you. Hate skids like this

"No one believes you" 
You and minesraft2 are the only person saying shit, I made my code.

**Comment by Minesraft2** [comment]
> > > they were not
> > 
> > 
> > Nice try kiddo, no one believes you. Hate skids like this
> 
> "No one believes you" You and minesraft2 are the only person saying shit, I made my code.

tell that to the dmca takedown

**Comment by prndndndndnndnd** [comment]
yes

**Comment by Thing3487** [comment]
> > > they were not
> > 
> > 
> > Nice try kiddo, no one believes you. Hate skids like this
> 
> "No one believes you" You and minesraft2 are the only person saying shit, I made my code.

💀
